const BUILTINS = new Set([
    "print",
    "sleep",
    "range",
    "len",
    "abs",
    "math",
    "int",
    "float",
    "bool",
    "chr",
    "ord",
    "tuple",
    "set",
    "frozenset",
    "bytes",
    "bytearray",
    "dict",
]);
const SYSTEM_HELPERS = [
    "__add",
    "__sub",
    "__mul",
    "__div",
    "__eq",
    "__ne",
    "__lt",
    "__gt",
    "__le",
    "__ge",
    "__true",
    "__and",
    "__or",
    "__item",
    "__iter",
    "__slice",
    "__tuple",
    "__set",
    "__dict",
    "__bytes",
    "__pow",
    "__floordiv",
    "__mod",
    "__and_bw",
    "__or_bw",
    "__xor_bw",
    "__lshift",
    "__rshift",
    "__invert",
    "__in",
];
const OP_TO_HELPER = {
    "+": "__add",
    "-": "__sub",
    "*": "__mul",
    "/": "__div",
    "//": "__floordiv",
    "%": "__mod",
    "**": "__pow",
    "&": "__and_bw",
    "|": "__or_bw",
    "^": "__xor_bw",
    "<<": "__lshift",
    ">>": "__rshift",
    "==": "__eq",
    "!=": "__ne",
    "<": "__lt",
    ">": "__gt",
    "<=": "__le",
    ">=": "__ge",
    in: "__in",
};
export class Compiler {
    indentLevel = 0;
    tmpCounter = 0;
    indent() {
        return "  ".repeat(this.indentLevel);
    }
    nextTmp(name) {
        return `__tmp_${name}_${this.tmpCounter++}`;
    }
    compileJS(program) {
        let js = "// Generated by Python-to-JavaScript\n";
        js += "export async function main_wrapper(__runtime) {\n";
        this.indentLevel++;
        js += `${this.indent()}const __globals = Object.create(__runtime);\n`;
        // Identify used built-ins and system helpers to selectively assign them
        const usedBuiltins = this.collectUsedBuiltins(program.body);
        // Identify top-level variables and functions
        const topLevelVars = this.collectAssignedVars(program.body);
        for (const node of program.body) {
            if (node.type === "FunctionDef") {
                topLevelVars.add(node.name);
            }
        }
        // Map builtins that are used and not shadowed at top-level
        for (const b of BUILTINS) {
            if (usedBuiltins.has(b) && !topLevelVars.has(b)) {
                js += `${this.indent()}const ${b} = __runtime.${b};\n`;
            }
        }
        // Map system helpers that are used
        for (const h of SYSTEM_HELPERS) {
            if (usedBuiltins.has(h)) {
                js += `${this.indent()}const ${h} = __runtime.${h};\n`;
            }
        }
        // Declare top-level variables (excluding functions which use 'async function')
        const varsToDeclare = new Set(topLevelVars);
        for (const node of program.body) {
            if (node.type === "FunctionDef") {
                varsToDeclare.delete(node.name);
            }
        }
        if (varsToDeclare.size > 0) {
            js += `${this.indent()}let ${Array.from(varsToDeclare).join(", ")};\n`;
        }
        js += "\n";
        // First pass: identify all functions to declare them at the top scope
        for (const node of program.body) {
            if (node.type === "FunctionDef") {
                js += this.compileNode(node) + "\n";
                js += `${this.indent()}__globals.${node.name} = ${node.name};\n`;
            }
        }
        // Second pass: compile top-level statements
        let mainCalled = false;
        const statements = program.body.filter((n) => n.type !== "FunctionDef");
        for (let i = 0; i < statements.length; i++) {
            const node = statements[i];
            const isLast = i === statements.length - 1;
            const isMainCall = node.type === "CallExpression" &&
                (typeof node.callee === "string" ? node.callee === "main" : false);
            if (isMainCall) {
                mainCalled = true;
                if (isLast) {
                    js += `${this.indent()}__globals.__result__ = ${this.compileNode(node)};\n`;
                    js += `${this.indent()}return __globals;\n`;
                    continue;
                }
            }
            const compiled = this.compileNode(node);
            if (compiled) {
                js += `${this.indent()}${compiled};\n`;
            }
        }
        // Try to call main() if it exists and hasn't been called
        if (!mainCalled) {
            js += `\n${this.indent()}if (typeof main === 'function') {\n`;
            js += `${this.indent()}  __globals.__result__ = await main();\n`;
            js += `${this.indent()}}\n`;
        }
        js += `\n${this.indent()}return __globals;\n`;
        this.indentLevel--;
        js += "}\n";
        return js;
    }
    collectUsedBuiltins(nodes) {
        const used = new Set();
        const stack = [...nodes];
        while (stack.length > 0) {
            const node = stack.pop();
            if (node.type === "CallExpression") {
                if (typeof node.callee === "string") {
                    if (BUILTINS.has(node.callee))
                        used.add(node.callee);
                    if (node.callee === "next") {
                        used.add("__item"); // next(g) uses helper for internal done/value check? No, next is explicit.
                        // Actually next() implementation in compiler.ts uses .next() call.
                    }
                }
                stack.push(...node.args);
                if (typeof node.callee !== "string")
                    stack.push(node.callee);
            }
            else if (node.type === "BinaryExpression") {
                if (OP_TO_HELPER[node.operator]) {
                    used.add(OP_TO_HELPER[node.operator]);
                }
                else if (node.operator === "and") {
                    used.add("__and");
                }
                else if (node.operator === "or") {
                    used.add("__or");
                }
                else if (node.operator === "not in") {
                    used.add("__in");
                }
                stack.push(node.left, node.right);
            }
            else if (node.type === "UnaryExpression") {
                if (node.operator === "not")
                    used.add("__true");
                if (node.operator === "~")
                    used.add("__invert");
                stack.push(node.argument);
            }
            else if (node.type === "If") {
                used.add("__true");
                stack.push(node.condition);
                stack.push(...node.thenBranch);
                if (node.elseBranch)
                    stack.push(...node.elseBranch);
            }
            else if (node.type === "While" || node.type === "DoWhile") {
                used.add("__true");
                stack.push(node.condition);
                stack.push(...node.body);
            }
            else if (node.type === "For") {
                used.add("__iter");
                if (node.iterable)
                    stack.push(node.iterable);
                if (node.start) {
                    stack.push(node.start);
                    used.add("__lt"); // for (i=start; i<stop; i++)
                    used.add("__add");
                }
                if (node.stop)
                    stack.push(node.stop);
                stack.push(...node.body);
            }
            else if (node.type === "Assignment") {
                stack.push(node.value);
            }
            else if (node.type === "Return" || node.type === "Yield") {
                if (node.value)
                    stack.push(node.value);
            }
            else if (node.type === "FunctionDef") {
                stack.push(...node.body);
            }
            else if (node.type === "List") {
                stack.push(...node.elements);
            }
            else if (node.type === "Tuple") {
                used.add("__tuple");
                stack.push(...node.elements);
            }
            else if (node.type === "Set") {
                used.add("__set");
                stack.push(...node.elements);
            }
            else if (node.type === "Dict") {
                used.add("__dict");
                for (const e of node.entries)
                    stack.push(e.key, e.value);
            }
            else if (node.type === "Bytes") {
                used.add("__bytes");
            }
            else if (node.type === "Subscript") {
                used.add("__item");
                stack.push(node.value, node.index);
            }
            else if (node.type === "Slice") {
                used.add("__slice");
                if (node.start)
                    stack.push(node.start);
                if (node.stop)
                    stack.push(node.stop);
                if (node.step)
                    stack.push(node.step);
            }
            else if (node.type === "ListComprehension" ||
                node.type === "SetComprehension" ||
                node.type === "DictComprehension") {
                used.add("__iter");
                stack.push(node.iterable);
                if (node.condition) {
                    used.add("__true");
                    stack.push(node.condition);
                }
                if (node.type === "ListComprehension" ||
                    node.type === "SetComprehension") {
                    stack.push(node.expression);
                }
                else {
                    stack.push(node.key, node.value);
                }
            }
            else if (node.type === "FString") {
                for (const p of node.parts) {
                    if (typeof p !== "string")
                        stack.push(p);
                }
            }
            else if (node.type === "With") {
                stack.push(node.expression);
                stack.push(...node.body);
            }
            else if (node.type === "MemberAccess") {
                stack.push(node.object);
            }
        }
        return used;
    }
    collectAssignedVars(nodes) {
        const vars = new Set();
        const stack = [...nodes];
        while (stack.length > 0) {
            const node = stack.pop();
            if (node.type === "Assignment") {
                vars.add(node.target);
            }
            else if (node.type === "For") {
                vars.add(node.iterator);
                stack.push(...node.body);
            }
            else if (node.type === "With") {
                if (node.target)
                    vars.add(node.target);
                stack.push(...node.body);
            }
            else if (node.type === "If") {
                stack.push(...node.thenBranch);
                if (node.elseBranch)
                    stack.push(...node.elseBranch);
            }
            else if (node.type === "While" || node.type === "DoWhile") {
                stack.push(...node.body);
            }
        }
        return vars;
    }
    compileNode(node) {
        switch (node.type) {
            case "Program":
                return node.body.map((n) => this.compileNode(n)).join("\n");
            case "FunctionDef":
                return this.compileFunctionDef(node);
            case "Assignment":
                return this.compileAssignment(node);
            case "BinaryExpression":
                return this.compileBinaryExpression(node);
            case "UnaryExpression":
                return this.compileUnaryExpression(node);
            case "Literal":
                if (typeof node.value === "string") {
                    return JSON.stringify(node.value);
                }
                if (typeof node.value === "bigint") {
                    return node.value.toString() + "n";
                }
                return node.value.toString();
            case "Identifier":
                return node.name;
            case "Return":
                return `return ${node.value ? this.compileNode(node.value) : "undefined"}`;
            case "While":
                return this.compileWhile(node);
            case "DoWhile":
                return this.compileDoWhile(node);
            case "For":
                return this.compileFor(node);
            case "If":
                return this.compileIf(node);
            case "CallExpression":
                return this.compileCall(node);
            case "List":
                return `[${node.elements.map((e) => this.compileNode(e)).join(", ")}]`;
            case "Tuple":
                return `__tuple([${node.elements.map((e) => this.compileNode(e)).join(", ")}])`;
            case "Set":
                return `__set([${node.elements.map((e) => this.compileNode(e)).join(", ")}])`;
            case "Dict":
                return `__dict([${node.entries.map((e) => `[${this.compileNode(e.key)}, ${this.compileNode(e.value)}]`).join(", ")}])`;
            case "Bytes":
                return `__bytes(${JSON.stringify(node.value)})`;
            case "Subscript":
                return this.compileSubscript(node);
            case "ListComprehension":
                return this.compileListComprehension(node);
            case "SetComprehension":
                return this.compileSetComprehension(node);
            case "DictComprehension":
                return this.compileDictComprehension(node);
            case "FString":
                return this.compileFString(node);
            case "Yield":
                return `yield ${this.compileNode(node.value)}`;
            case "With":
                return this.compileWith(node);
            case "MemberAccess":
                return `${this.compileNode(node.object)}.${node.member}`;
            case "Pass":
                return "";
            default:
                throw new Error(`Unknown node type: ${node.type}`);
        }
    }
    compileFunctionDef(node) {
        const isGenerator = this.containsYield(node.body);
        const funcType = isGenerator ? "async function*" : "async function";
        const params = node.params.join(", ");
        let js = `${this.indent()}${funcType} ${node.name}(${params}) {\n`;
        this.indentLevel++;
        // Declare local variables (excluding params)
        const localVars = this.collectAssignedVars(node.body);
        for (const p of node.params)
            localVars.delete(p);
        if (localVars.size > 0) {
            js += `${this.indent()}let ${Array.from(localVars).join(", ")};\n`;
        }
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled) {
                js += `${this.indent()}${compiled};\n`;
            }
        }
        this.indentLevel--;
        js += `${this.indent()}}\n`;
        return js;
    }
    containsYield(nodes) {
        for (const node of nodes) {
            if (node.type === "Yield")
                return true;
            if ("body" in node && Array.isArray(node.body)) {
                if (this.containsYield(node.body))
                    return true;
            }
            if (node.type === "If") {
                if (this.containsYield(node.thenBranch))
                    return true;
                if (node.elseBranch && this.containsYield(node.elseBranch))
                    return true;
            }
        }
        return false;
    }
    compileAssignment(node) {
        return `${node.target} = ${this.compileNode(node.value)}`;
    }
    compileBinaryExpression(node) {
        const left = this.compileNode(node.left);
        const right = this.compileNode(node.right);
        const op = node.operator;
        if (op === "and") {
            return `(await __and(async () => ${left}, async () => ${right}))`;
        }
        if (op === "or") {
            return `(await __or(async () => ${left}, async () => ${right}))`;
        }
        if (op === "not in") {
            return `(!__in(${left}, ${right}))`;
        }
        const helper = OP_TO_HELPER[op];
        if (helper) {
            return `${helper}(${left}, ${right})`;
        }
        throw new Error(`Unsupported binary operator: ${op}`);
    }
    compileUnaryExpression(node) {
        const arg = this.compileNode(node.argument);
        const op = node.operator;
        if (op === "not") {
            return `(!__true(${arg}))`;
        }
        if (op === "~") {
            return `__invert(${arg})`;
        }
        return `${op}${arg}`;
    }
    compileIf(node) {
        let js = `if (__true(${this.compileNode(node.condition)})) {\n`;
        this.indentLevel++;
        for (const stmt of node.thenBranch) {
            const compiled = this.compileNode(stmt);
            if (compiled)
                js += `${this.indent()}${compiled};\n`;
        }
        this.indentLevel--;
        js += `${this.indent()}}`;
        if (node.elseBranch) {
            js += ` else {\n`;
            this.indentLevel++;
            for (const stmt of node.elseBranch) {
                const compiled = this.compileNode(stmt);
                if (compiled)
                    js += `${this.indent()}${compiled};\n`;
            }
            this.indentLevel--;
            js += `${this.indent()}}`;
        }
        return js;
    }
    compileWhile(node) {
        let js = `while (__true(${this.compileNode(node.condition)})) {\n`;
        this.indentLevel++;
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled)
                js += `${this.indent()}${compiled};\n`;
        }
        this.indentLevel--;
        js += `${this.indent()}}`;
        return js;
    }
    compileDoWhile(node) {
        let js = `do {\n`;
        this.indentLevel++;
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled)
                js += `${this.indent()}${compiled};\n`;
        }
        this.indentLevel--;
        js += `${this.indent()}} while (__true(${this.compileNode(node.condition)}))`;
        return js;
    }
    compileFor(node) {
        if (node.iterable) {
            const iterable = this.compileNode(node.iterable);
            const tmpItem = this.nextTmp("item");
            // Use a runtime helper to handle both sync and async iterators efficiently
            let js = `for await (const ${tmpItem} of __iter(${iterable})) {\n`;
            this.indentLevel++;
            js += `${this.indent()}${node.iterator} = ${tmpItem};\n`;
            for (const stmt of node.body) {
                const compiled = this.compileNode(stmt);
                if (compiled)
                    js += `${this.indent()}${compiled};\n`;
            }
            this.indentLevel--;
            js += `${this.indent()}}`;
            return js;
        }
        else if (node.start && node.stop) {
            const start = this.compileNode(node.start);
            const stop = this.compileNode(node.stop);
            // Use the already-declared iterator directly
            let js = `for (${node.iterator} = ${start}; __lt(${node.iterator}, ${stop}); ${node.iterator} = __add(${node.iterator}, 1)) {\n`;
            this.indentLevel++;
            for (const stmt of node.body) {
                const compiled = this.compileNode(stmt);
                if (compiled)
                    js += `${this.indent()}${compiled};\n`;
            }
            this.indentLevel--;
            js += `${this.indent()}}`;
            return js;
        }
        throw new Error("Malformed For loop node: missing iterable or range bounds");
    }
    compileCall(node) {
        const args = node.args.map((a) => this.compileNode(a)).join(", ");
        if (typeof node.callee === "string") {
            if (node.callee === "next") {
                if (node.args.length === 0)
                    throw new Error("next() requires at least one argument");
                const receiver = this.compileNode(node.args[0]);
                if (node.args.length === 1) {
                    return `(await ${receiver}.next()).value`;
                }
                else {
                    // next(g, default)
                    const tmpRes = this.nextTmp("next_res");
                    const defaultValue = this.compileNode(node.args[1]);
                    return `(await (async () => {
            const ${tmpRes} = await ${receiver}.next();
            return ${tmpRes}.done ? ${defaultValue} : ${tmpRes}.value;
          })())`;
                }
            }
            if (node.callee === "sleep") {
                return `(await sleep(${args}))`;
            }
            if (BUILTINS.has(node.callee)) {
                return `${node.callee}(${args})`;
            }
            return `(await ${node.callee}(${args}))`;
        }
        if (node.callee.type === "MemberAccess") {
            const obj = this.compileNode(node.callee.object);
            const member = node.callee.member;
            const tmpObj = this.nextTmp("obj");
            const tmpFallback = this.nextTmp("fallback");
            // Handle fallback to runtime for member calls (Python-style methods)
            return `(await (async () => {
        const ${tmpObj} = ${obj};
        if (typeof ${tmpObj}.${member} === 'function') {
          return await ${tmpObj}.${member}(${args});
        }
        const ${tmpFallback} = __globals.${member};
        if (typeof ${tmpFallback} === 'function') {
          return await ${tmpFallback}(${tmpObj}${args ? ", " + args : ""});
        }
        throw new Error("${member} is not a function");
      })())`;
        }
        const callee = this.compileNode(node.callee);
        return `(await ${callee}(${args}))`;
    }
    compileSubscript(node) {
        if (node.index.type === "Slice") {
            return this.compileSlice(this.compileNode(node.value), node.index);
        }
        const obj = this.compileNode(node.value);
        const idx = this.compileNode(node.index);
        return `__item(${obj}, ${idx})`;
    }
    compileSlice(obj, slice) {
        const start = slice.start ? this.compileNode(slice.start) : "undefined";
        const stop = slice.stop ? this.compileNode(slice.stop) : "undefined";
        const step = slice.step ? this.compileNode(slice.step) : "1";
        return `__slice(${obj}, ${start}, ${stop}, ${step})`;
    }
    compileListComprehension(node) {
        const expr = this.compileNode(node.expression);
        const iterable = this.compileNode(node.iterable);
        const cond = node.condition
            ? `__true(${this.compileNode(node.condition)})`
            : "true";
        const tmpItem = this.nextTmp("item");
        return `(await (async () => {
      const res = [];
      for await (const ${tmpItem} of __iter(${iterable})) {
        const ${node.item} = ${tmpItem};
        if (${cond}) res.push(${expr});
      }
      return res;
    })())`;
    }
    compileSetComprehension(node) {
        const expr = this.compileNode(node.expression);
        const iterable = this.compileNode(node.iterable);
        const cond = node.condition
            ? `__true(${this.compileNode(node.condition)})`
            : "true";
        const tmpItem = this.nextTmp("item");
        return `(await (async () => {
      const res = new Set();
      for await (const ${tmpItem} of __iter(${iterable})) {
        const ${node.item} = ${tmpItem};
        if (${cond}) res.add(${expr});
      }
      return res;
    })())`;
    }
    compileDictComprehension(node) {
        const key = this.compileNode(node.key);
        const value = this.compileNode(node.value);
        const iterable = this.compileNode(node.iterable);
        const cond = node.condition
            ? `__true(${this.compileNode(node.condition)})`
            : "true";
        const tmpItem = this.nextTmp("item");
        return `(await (async () => {
      const res = {};
      for await (const ${tmpItem} of __iter(${iterable})) {
        const ${node.item} = ${tmpItem};
        if (${cond}) res[${key}] = ${value};
      }
      return res;
    })())`;
    }
    compileFString(node) {
        const parts = node.parts
            .map((p) => {
            if (typeof p === "string") {
                return p
                    .replace(/\\/g, "\\\\")
                    .replace(/`/g, "\\`")
                    .replace(/\$\{/g, "\\${");
            }
            return `\${${this.compileNode(p)}}`;
        })
            .join("");
        return `(\`${parts}\`)`;
    }
    compileWith(node) {
        const expr = this.compileNode(node.expression);
        const target = node.target;
        const tmpMgr = this.nextTmp("mgr");
        const tmpIsMethod = this.nextTmp("is_method");
        const tmpEnter = this.nextTmp("enter");
        const tmpExit = this.nextTmp("exit");
        let js = `{\n`;
        this.indentLevel++;
        js += `${this.indent()}const ${tmpMgr} = ${expr};\n`;
        js += `${this.indent()}const ${tmpIsMethod} = typeof ${tmpMgr}.__enter__ === 'function';\n`;
        js += `${this.indent()}const ${tmpEnter} = ${tmpIsMethod} ? ${tmpMgr}.__enter__.bind(${tmpMgr}) : __globals.__enter__;\n`;
        js += `${this.indent()}const ${tmpExit} = typeof ${tmpMgr}.__exit__ === 'function' ? ${tmpMgr}.__exit__.bind(${tmpMgr}) : __globals.__exit__;\n`;
        js += `${this.indent()}if (typeof ${tmpEnter} !== 'function') throw new Error("Object does not support the context manager protocol (missing __enter__)");\n`;
        js += `${this.indent()}if (typeof ${tmpExit} !== 'function') throw new Error("Object does not support the context manager protocol (missing __exit__)");\n`;
        const enterCall = `await (${tmpIsMethod} ? ${tmpEnter}() : ${tmpEnter}(${tmpMgr}))`;
        if (target) {
            js += `${this.indent()}${target} = ${enterCall};\n`;
        }
        else {
            js += `${this.indent()}${enterCall};\n`;
        }
        js += `${this.indent()}try {\n`;
        this.indentLevel++;
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled)
                js += `${this.indent()}${compiled};\n`;
        }
        this.indentLevel--;
        js += `${this.indent()}} finally {\n`;
        this.indentLevel++;
        js += `${this.indent()}await (${tmpIsMethod} ? ${tmpExit}(null, null, null) : ${tmpExit}(${tmpMgr}, null, null, null));\n`;
        this.indentLevel--;
        js += `${this.indent()}}\n`;
        this.indentLevel--;
        js += `${this.indent()}}`;
        return js;
    }
}
