export class Compiler {
    indentLevel = 0;
    indent() {
        return "  ".repeat(this.indentLevel);
    }
    compileJS(program) {
        let js = "// Generated by Python-to-JavaScript\n";
        js += "export async function main_wrapper(runtime) {\n";
        this.indentLevel++;
        js += `${this.indent()}const { print, sleep, range, len, abs, math } = runtime;\n`;
        // Declare top-level variables
        const topLevelVars = this.collectAssignedVars(program.body);
        if (topLevelVars.size > 0) {
            js += `${this.indent()}let ${Array.from(topLevelVars).join(", ")};\n`;
        }
        js += "\n";
        // First pass: identify all functions to declare them at the top scope
        for (const node of program.body) {
            if (node.type === "FunctionDef") {
                js += this.compileNode(node) + "\n";
                js += `${this.indent()}runtime.${node.name} = ${node.name};\n`;
            }
        }
        // Second pass: compile top-level statements
        let mainCalled = false;
        const statements = program.body.filter((n) => n.type !== "FunctionDef");
        for (let i = 0; i < statements.length; i++) {
            const node = statements[i];
            const isLast = i === statements.length - 1;
            const isMainCall = node.type === "CallExpression" &&
                (typeof node.callee === "string" ? node.callee === "main" : false);
            if (isMainCall) {
                mainCalled = true;
                if (isLast) {
                    js += `${this.indent()}return ${this.compileNode(node)};\n`;
                    continue;
                }
            }
            const compiled = this.compileNode(node);
            if (compiled) {
                js += `${this.indent()}${compiled};\n`;
            }
        }
        // Try to call main() if it exists and hasn't been called
        if (!mainCalled) {
            js += `\n${this.indent()}if (typeof main === 'function') {\n`;
            js += `${this.indent()}  return await main();\n`;
            js += `${this.indent()}}\n`;
        }
        this.indentLevel--;
        js += "}\n";
        return js;
    }
    collectAssignedVars(nodes) {
        const vars = new Set();
        const stack = [...nodes];
        while (stack.length > 0) {
            const node = stack.pop();
            if (node.type === "Assignment") {
                vars.add(node.target);
            }
            else if (node.type === "For") {
                vars.add(node.iterator);
                stack.push(...node.body);
            }
            else if (node.type === "With") {
                if (node.target)
                    vars.add(node.target);
                stack.push(...node.body);
            }
            else if (node.type === "If") {
                stack.push(...node.thenBranch);
                if (node.elseBranch)
                    stack.push(...node.elseBranch);
            }
            else if (node.type === "While" || node.type === "DoWhile") {
                stack.push(...node.body);
            }
            else if (node.type === "ListComprehension" ||
                node.type === "DictComprehension") {
                // Comprehension variables are local to the comprehension in Python 3
                // and our transpilation uses an IIFE which has its own 'const item'
            }
        }
        return vars;
    }
    compileNode(node) {
        switch (node.type) {
            case "Program":
                return node.body.map((n) => this.compileNode(n)).join("\n");
            case "FunctionDef":
                return this.compileFunctionDef(node);
            case "Assignment":
                return this.compileAssignment(node);
            case "BinaryExpression":
                return this.compileBinaryExpression(node);
            case "UnaryExpression":
                return this.compileUnaryExpression(node);
            case "Literal":
                if (typeof node.value === "string") {
                    return JSON.stringify(node.value);
                }
                return node.value.toString();
            case "Identifier":
                return node.name;
            case "Return":
                return `return ${node.value ? this.compileNode(node.value) : "undefined"}`;
            case "While":
                return this.compileWhile(node);
            case "DoWhile":
                return this.compileDoWhile(node);
            case "For":
                return this.compileFor(node);
            case "If":
                return this.compileIf(node);
            case "CallExpression":
                return this.compileCall(node);
            case "List":
                return `[${node.elements.map((e) => this.compileNode(e)).join(", ")}]`;
            case "Subscript":
                return this.compileSubscript(node);
            case "ListComprehension":
                return this.compileListComprehension(node);
            case "DictComprehension":
                return this.compileDictComprehension(node);
            case "FString":
                return this.compileFString(node);
            case "Yield":
                return `yield ${this.compileNode(node.value)}`;
            case "With":
                return this.compileWith(node);
            case "MemberAccess":
                return `${this.compileNode(node.object)}.${node.member}`;
            case "Pass":
                return "";
            default:
                throw new Error(`Unknown node type: ${node.type}`);
        }
    }
    compileFunctionDef(node) {
        const isGenerator = this.containsYield(node.body);
        const funcType = isGenerator ? "async function*" : "async function";
        const params = node.params.join(", ");
        let js = `${this.indent()}${funcType} ${node.name}(${params}) {\n`;
        this.indentLevel++;
        // Declare local variables (excluding params)
        const localVars = this.collectAssignedVars(node.body);
        for (const p of node.params)
            localVars.delete(p);
        if (localVars.size > 0) {
            js += `${this.indent()}let ${Array.from(localVars).join(", ")};\n`;
        }
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled) {
                js += `${this.indent()}${compiled};\n`;
            }
        }
        this.indentLevel--;
        js += `${this.indent()}}\n`;
        return js;
    }
    containsYield(nodes) {
        for (const node of nodes) {
            if (node.type === "Yield")
                return true;
            if ("body" in node && Array.isArray(node.body)) {
                if (this.containsYield(node.body))
                    return true;
            }
            if (node.type === "If") {
                if (this.containsYield(node.thenBranch))
                    return true;
                if (node.elseBranch && this.containsYield(node.elseBranch))
                    return true;
            }
        }
        return false;
    }
    compileAssignment(node) {
        return `${node.target} = ${this.compileNode(node.value)}`;
    }
    compileBinaryExpression(node) {
        const left = this.compileNode(node.left);
        const right = this.compileNode(node.right);
        let op = node.operator;
        if (op === "and")
            op = "&&";
        if (op === "or")
            op = "||";
        if (op === "==")
            op = "===";
        if (op === "!=")
            op = "!==";
        return `(${left} ${op} ${right})`;
    }
    compileUnaryExpression(node) {
        const arg = this.compileNode(node.argument);
        let op = node.operator;
        if (op === "not")
            op = "!";
        return `${op}${arg}`;
    }
    compileIf(node) {
        let js = `if (${this.compileNode(node.condition)}) {\n`;
        this.indentLevel++;
        for (const stmt of node.thenBranch) {
            const compiled = this.compileNode(stmt);
            if (compiled)
                js += `${this.indent()}${compiled};\n`;
        }
        this.indentLevel--;
        js += `${this.indent()}}`;
        if (node.elseBranch) {
            js += ` else {\n`;
            this.indentLevel++;
            for (const stmt of node.elseBranch) {
                const compiled = this.compileNode(stmt);
                if (compiled)
                    js += `${this.indent()}${compiled};\n`;
            }
            this.indentLevel--;
            js += `${this.indent()}}`;
        }
        return js;
    }
    compileWhile(node) {
        let js = `while (${this.compileNode(node.condition)}) {\n`;
        this.indentLevel++;
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled)
                js += `${this.indent()}${compiled};\n`;
        }
        this.indentLevel--;
        js += `${this.indent()}}`;
        return js;
    }
    compileDoWhile(node) {
        let js = `do {\n`;
        this.indentLevel++;
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled)
                js += `${this.indent()}${compiled};\n`;
        }
        this.indentLevel--;
        js += `${this.indent()}} while (${this.compileNode(node.condition)})`;
        return js;
    }
    compileFor(node) {
        if (node.iterable) {
            const iterable = this.compileNode(node.iterable);
            let js = `for await (const ${node.iterator} of ${iterable}) {\n`;
            this.indentLevel++;
            for (const stmt of node.body) {
                const compiled = this.compileNode(stmt);
                if (compiled)
                    js += `${this.indent()}${compiled};\n`;
            }
            this.indentLevel--;
            js += `${this.indent()}}`;
            return js;
        }
        else if (node.start && node.stop) {
            const start = this.compileNode(node.start);
            const stop = this.compileNode(node.stop);
            let js = `for (let ${node.iterator} = ${start}; ${node.iterator} < ${stop}; ${node.iterator}++) {\n`;
            this.indentLevel++;
            for (const stmt of node.body) {
                const compiled = this.compileNode(stmt);
                if (compiled)
                    js += `${this.indent()}${compiled};\n`;
            }
            this.indentLevel--;
            js += `${this.indent()}}`;
            return js;
        }
        return "";
    }
    compileCall(node) {
        const args = node.args.map((a) => this.compileNode(a)).join(", ");
        if (typeof node.callee === "string") {
            if (node.callee === "next") {
                return `(await ${args}.next()).value`;
            }
            return `(await ${node.callee}(${args}))`;
        }
        if (node.callee.type === "MemberAccess") {
            const obj = this.compileNode(node.callee.object);
            const member = node.callee.member;
            // Handle fallback to runtime for member calls
            return `(await (async () => {
        const _obj = ${obj};
        const _fn = typeof _obj.${member} === 'function' ? _obj.${member}.bind(_obj) : runtime.${member};
        if (typeof _fn !== 'function') throw new Error("${member} is not a function");
        return await _fn(_obj, ${args});
      })())`;
        }
        const callee = this.compileNode(node.callee);
        return `(await ${callee}(${args}))`;
    }
    compileSubscript(node) {
        const obj = this.compileNode(node.value);
        if (node.index.type === "Slice") {
            return this.compileSlice(obj, node.index);
        }
        const idx = this.compileNode(node.index);
        return `${obj}[${idx} < 0 ? ${obj}.length + ${idx} : ${idx}]`;
    }
    compileSlice(obj, slice) {
        const start = slice.start ? this.compileNode(slice.start) : "undefined";
        const stop = slice.stop ? this.compileNode(slice.stop) : "undefined";
        const step = slice.step ? this.compileNode(slice.step) : "1";
        return `runtime._slice(${obj}, ${start}, ${stop}, ${step})`;
    }
    compileListComprehension(node) {
        const expr = this.compileNode(node.expression);
        const iterable = this.compileNode(node.iterable);
        const cond = node.condition ? this.compileNode(node.condition) : "true";
        return `(await (async () => {
      const res = [];
      for await (const ${node.item} of ${iterable}) {
        if (${cond}) res.push(${expr});
      }
      return res;
    })())`;
    }
    compileDictComprehension(node) {
        const key = this.compileNode(node.key);
        const value = this.compileNode(node.value);
        const iterable = this.compileNode(node.iterable);
        const cond = node.condition ? this.compileNode(node.condition) : "true";
        return `(await (async () => {
      const res = {};
      for await (const ${node.item} of ${iterable}) {
        if (${cond}) res[${key}] = ${value};
      }
      return res;
    })())`;
    }
    compileFString(node) {
        const parts = node.parts
            .map((p) => {
            if (typeof p === "string")
                return JSON.stringify(p);
            return `String(${this.compileNode(p)})`;
        })
            .join(" + ");
        return `(${parts})`;
    }
    compileWith(node) {
        const expr = this.compileNode(node.expression);
        const target = node.target;
        const mgrVar = `_mgr_${this.indentLevel}`;
        let js = `{\n`;
        this.indentLevel++;
        js += `${this.indent()}const ${mgrVar} = ${expr};\n`;
        js += `${this.indent()}const _enter = typeof ${mgrVar}.__enter__ === 'function' ? ${mgrVar}.__enter__.bind(${mgrVar}) : runtime.__enter__;\n`;
        js += `${this.indent()}const _exit = typeof ${mgrVar}.__exit__ === 'function' ? ${mgrVar}.__exit__.bind(${mgrVar}) : runtime.__exit__;\n`;
        js += `${this.indent()}const ${target || "_unused"} = await _enter(${mgrVar});\n`;
        js += `${this.indent()}try {\n`;
        this.indentLevel++;
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled)
                js += `${this.indent()}${compiled};\n`;
        }
        this.indentLevel--;
        js += `${this.indent()}} finally {\n`;
        this.indentLevel++;
        js += `${this.indent()}await _exit(${mgrVar}, null, null, null);\n`;
        this.indentLevel--;
        js += `${this.indent()}}\n`;
        this.indentLevel--;
        js += `${this.indent()}}`;
        return js;
    }
    // Compatibility methods
    compileWAT(program) {
        return this.compileJS(program);
    }
    compileWASM(program) {
        return new TextEncoder().encode(this.compileJS(program));
    }
}
