const BUILTINS = new Set([
    "print",
    "sleep",
    "range",
    "len",
    "abs",
    "math",
    "int",
    "float",
    "bool",
    "str",
    "chr",
    "ord",
    "hex",
    "bin",
    "oct",
    "round",
    "divmod",
    "list",
    "tuple",
    "set",
    "frozenset",
    "bytes",
    "bytearray",
    "dict",
    "min",
    "max",
    "sum",
    "any",
    "all",
    "enumerate",
    "zip",
    "reversed",
    "sorted",
    "type",
    "isinstance",
    "callable",
    "map",
    "filter",
    "reduce",
    "format",
    "split",
    "join",
    "strip",
    "replace",
    "find",
    "upper",
    "lower",
    "startswith",
    "endswith",
    "isalpha",
    "isdigit",
    "isspace",
    "isalnum",
    "islower",
    "isupper",
    "count",
    "append",
    "extend",
    "insert",
    "remove",
    "pop",
    "sort",
    "reverse",
    "get",
    "keys",
    "values",
    "items",
    "update",
    "clear",
    "copy",
    "__enter__",
    "__exit__",
]);
const ASYNC_BUILTINS = new Set([
    "sleep",
    "__call",
    "__enter__",
    "__exit__",
    "map",
    "filter",
    "reduce",
]);
const SYSTEM_HELPERS = [
    "__add",
    "__sub",
    "__mul",
    "__div",
    "__eq",
    "__ne",
    "__lt",
    "__gt",
    "__le",
    "__ge",
    "__true",
    "__and",
    "__or",
    "__item",
    "__iter",
    "__slice",
    "__tuple",
    "__set",
    "__dict",
    "__bytes",
    "__pow",
    "__floordiv",
    "__mod",
    "__and_bw",
    "__or_bw",
    "__xor_bw",
    "__lshift",
    "__rshift",
    "__invert",
    "__in",
    "__call",
    "__call_method",
    "__unpack",
    "__set_item",
];
const OP_TO_HELPER = {
    "+": "__add",
    "-": "__sub",
    "*": "__mul",
    "/": "__div",
    "//": "__floordiv",
    "%": "__mod",
    "**": "__pow",
    "&": "__and_bw",
    "|": "__or_bw",
    "^": "__xor_bw",
    "<<": "__lshift",
    ">>": "__rshift",
    "==": "__eq",
    "!=": "__ne",
    "<": "__lt",
    ">": "__gt",
    "<=": "__le",
    ">=": "__ge",
    in: "__in",
};
export class Compiler {
    indentLevel = 0;
    tmpCounter = 0;
    topLevelVars = new Set();
    shadowedBuiltins = new Set();
    currentLocalVars = []; // Stack for nested functions
    currentSelfName = null;
    indent() {
        return "  ".repeat(this.indentLevel);
    }
    nextTmp(name) {
        return `__tmp_${name}_${this.tmpCounter++}`;
    }
    isShadowed(name) {
        for (let i = this.currentLocalVars.length - 1; i >= 0; i--) {
            if (this.currentLocalVars[i].has(name))
                return true;
        }
        return this.topLevelVars.has(name);
    }
    compileJS(program) {
        this.topLevelVars = this.collectAssignedVars(program.body);
        for (const node of program.body) {
            if (node.type === "FunctionDef") {
                this.topLevelVars.add(node.name);
            }
        }
        // Identify ALL variables assigned anywhere in the program to detect potential shadowing
        const allAssignedVars = this.collectAllAssignedVars(program.body);
        this.shadowedBuiltins = new Set(Array.from(BUILTINS).filter((b) => allAssignedVars.has(b)));
        let js = "// Generated by Python-to-JavaScript\n";
        js += "export async function main_wrapper(__runtime) {\n";
        this.indentLevel++;
        js += `${this.indent()}const __globals = Object.create(__runtime);\n`;
        const usedBuiltins = this.collectUsedBuiltins(program.body);
        const preloaded = new Set();
        // Preload used built-ins.
        // If NOT shadowed anywhere, we can use bare names safely for mappings.
        for (const b of BUILTINS) {
            if (usedBuiltins.has(b) && !this.shadowedBuiltins.has(b)) {
                js += `${this.indent()}let ${b} = __runtime.${b};\n`;
                preloaded.add(b);
            }
        }
        // Map system helpers that are used (keep as const, internal-only)
        for (const h of SYSTEM_HELPERS) {
            if (usedBuiltins.has(h)) {
                js += `${this.indent()}const ${h} = __runtime.${h};\n`;
            }
        }
        const varsToDeclare = new Set(this.topLevelVars);
        for (const b of preloaded) {
            varsToDeclare.delete(b);
        }
        if (varsToDeclare.size > 0) {
            js += `${this.indent()}let ${Array.from(varsToDeclare).join(", ")};\n`;
        }
        js += "\n";
        let mainCalled = false;
        for (let i = 0; i < program.body.length; i++) {
            const node = program.body[i];
            const isLast = i === program.body.length - 1;
            const isMainCall = node.type === "CallExpression" &&
                (typeof node.callee === "string" ? node.callee === "main" : false);
            if (isMainCall) {
                mainCalled = true;
                if (isLast) {
                    js += `${this.indent()}__globals.__result__ = ${this.compileNode(node)};\n`;
                    js += `${this.indent()}return __globals;\n`;
                    continue;
                }
            }
            const compiled = this.compileNode(node);
            if (compiled) {
                const needsSemicolon = ![
                    "If",
                    "While",
                    "DoWhile",
                    "For",
                    "FunctionDef",
                    "With",
                    "Class",
                ].includes(node.type);
                js += `${this.indent()}${compiled}${needsSemicolon ? ";" : ""}\n`;
                if (node.type === "FunctionDef" || node.type === "Class") {
                    js += `${this.indent()}__globals.${node.name} = ${node.name};\n`;
                }
            }
        }
        if (!mainCalled) {
            js += `\n${this.indent()}if (typeof main === 'function') {\n`;
            js += `${this.indent()}  __globals.__result__ = await main();\n`;
            js += `${this.indent()}}\n`;
        }
        js += `\n${this.indent()}return __globals;\n`;
        this.indentLevel--;
        js += "}\n";
        return js;
    }
    collectUsedBuiltins(nodes) {
        const used = new Set();
        const stack = [...nodes];
        while (stack.length > 0) {
            const node = stack.pop();
            if (node.type === "CallExpression") {
                if (typeof node.callee === "string") {
                    if (BUILTINS.has(node.callee))
                        used.add(node.callee);
                    else
                        used.add("__call");
                    if (node.callee === "next") {
                        used.add("__item");
                    }
                }
                else if (node.callee.type === "MemberAccess") {
                    if (BUILTINS.has(node.callee.member))
                        used.add(node.callee.member);
                    else
                        used.add("__call_method");
                }
                else {
                    used.add("__call");
                }
                if (node.args.some((a) => a.name !== undefined)) {
                    used.add("__call");
                }
                for (const arg of node.args) {
                    stack.push(arg.value);
                }
                if (typeof node.callee !== "string")
                    stack.push(node.callee);
            }
            else if (node.type === "BinaryExpression") {
                if (OP_TO_HELPER[node.operator]) {
                    used.add(OP_TO_HELPER[node.operator]);
                }
                else if (node.operator === "and") {
                    used.add("__and");
                }
                else if (node.operator === "or") {
                    used.add("__or");
                }
                else if (node.operator === "not in") {
                    used.add("__in");
                }
                stack.push(node.left, node.right);
            }
            else if (node.type === "UnaryExpression") {
                if (node.operator === "not")
                    used.add("__true");
                if (node.operator === "~")
                    used.add("__invert");
                stack.push(node.argument);
            }
            else if (node.type === "If") {
                used.add("__true");
                stack.push(node.condition);
                stack.push(...node.thenBranch);
                if (node.elseBranch)
                    stack.push(...node.elseBranch);
            }
            else if (node.type === "IfExpression") {
                used.add("__true");
                stack.push(node.condition, node.thenBranch, node.elseBranch);
            }
            else if (node.type === "While" || node.type === "DoWhile") {
                used.add("__true");
                stack.push(node.condition);
                stack.push(...node.body);
            }
            else if (node.type === "For") {
                used.add("__iter");
                if (node.iterators.length > 1)
                    used.add("__item");
                if (node.iterable)
                    stack.push(node.iterable);
                if (node.start) {
                    stack.push(node.start);
                    used.add("__lt");
                    used.add("__add");
                }
                if (node.stop)
                    stack.push(node.stop);
                stack.push(...node.body);
            }
            else if (node.type === "Assignment") {
                used.add("__unpack");
                stack.push(node.value);
                for (const target of node.targets) {
                    if (target.type !== "Identifier" && target.type !== "StarTarget") {
                        stack.push(target);
                    }
                }
            }
            else if (node.type === "Return" || node.type === "Yield") {
                if (node.value)
                    stack.push(node.value);
            }
            else if (node.type === "FunctionDef") {
                stack.push(...node.body);
                for (const p of node.params) {
                    if (p.defaultValue)
                        stack.push(p.defaultValue);
                }
            }
            else if (node.type === "Global" || node.type === "Nonlocal") {
                // No children
            }
            else if (node.type === "List") {
                stack.push(...node.elements);
            }
            else if (node.type === "Tuple") {
                used.add("__tuple");
                stack.push(...node.elements);
            }
            else if (node.type === "Set") {
                used.add("__set");
                stack.push(...node.elements);
            }
            else if (node.type === "Dict") {
                used.add("__dict");
                for (const e of node.entries)
                    stack.push(e.key, e.value);
            }
            else if (node.type === "Bytes") {
                used.add("__bytes");
            }
            else if (node.type === "Subscript") {
                used.add("__item");
                stack.push(node.value, node.index);
            }
            else if (node.type === "Slice") {
                used.add("__slice");
                if (node.start)
                    stack.push(node.start);
                if (node.stop)
                    stack.push(node.stop);
                if (node.step)
                    stack.push(node.step);
            }
            else if (node.type === "ListComprehension" ||
                node.type === "SetComprehension" ||
                node.type === "DictComprehension") {
                used.add("__iter");
                stack.push(node.iterable);
                if (node.condition) {
                    used.add("__true");
                    stack.push(node.condition);
                }
                if (node.type === "ListComprehension" ||
                    node.type === "SetComprehension") {
                    stack.push(node.expression);
                }
                else {
                    stack.push(node.key, node.value);
                }
            }
            else if (node.type === "FString") {
                used.add("str");
                for (const p of node.parts) {
                    if (typeof p !== "string")
                        stack.push(p);
                }
            }
            else if (node.type === "With") {
                stack.push(node.expression);
                stack.push(...node.body);
                used.add("__enter__");
                used.add("__exit__");
            }
            else if (node.type === "Lambda") {
                stack.push(node.expression);
                for (const p of node.params) {
                    if (p.defaultValue)
                        stack.push(p.defaultValue);
                }
            }
            else if (node.type === "Class") {
                stack.push(...node.body);
                stack.push(...node.bases);
            }
            else if (node.type === "MemberAccess") {
                stack.push(node.object);
            }
        }
        return used;
    }
    collectAssignedVars(nodes) {
        const vars = new Set();
        const stack = [...nodes];
        const explicitScopes = new Set();
        while (stack.length > 0) {
            const node = stack.pop();
            if (node.type === "Assignment") {
                for (const target of node.targets) {
                    this.collectTargets(target, vars);
                }
            }
            else if (node.type === "FunctionDef") {
                vars.add(node.name);
            }
            else if (node.type === "Class") {
                vars.add(node.name);
            }
            else if (node.type === "Global" || node.type === "Nonlocal") {
                for (const name of node.names) {
                    explicitScopes.add(name);
                }
            }
            else if (node.type === "For") {
                for (const it of node.iterators)
                    vars.add(it);
                stack.push(...node.body);
            }
            else if (node.type === "With") {
                if (node.target)
                    vars.add(node.target);
                stack.push(...node.body);
            }
            else if (node.type === "If") {
                stack.push(...node.thenBranch);
                if (node.elseBranch)
                    stack.push(...node.elseBranch);
            }
            else if (node.type === "While" || node.type === "DoWhile") {
                stack.push(...node.body);
            }
        }
        for (const name of explicitScopes) {
            vars.delete(name);
        }
        return vars;
    }
    collectAllAssignedVars(nodes) {
        const vars = new Set();
        const stack = [...nodes];
        while (stack.length > 0) {
            const node = stack.pop();
            if (node.type === "Assignment") {
                for (const target of node.targets)
                    this.collectTargets(target, vars);
            }
            else if (node.type === "FunctionDef") {
                vars.add(node.name);
                stack.push(...node.body);
            }
            else if (node.type === "Class") {
                vars.add(node.name);
                stack.push(...node.body);
            }
            else if (node.type === "For") {
                for (const it of node.iterators)
                    vars.add(it);
                stack.push(...node.body);
            }
            else if (node.type === "With") {
                if (node.target)
                    vars.add(node.target);
                stack.push(...node.body);
            }
            else if (node.type === "Lambda") {
                stack.push(node.expression);
            }
            else if ("body" in node && Array.isArray(node.body)) {
                stack.push(...node.body);
            }
            else if (node.type === "If") {
                stack.push(...node.thenBranch);
                if (node.elseBranch)
                    stack.push(...node.elseBranch);
            }
        }
        return vars;
    }
    collectTargets(node, vars) {
        if (node.type === "Identifier") {
            vars.add(node.name);
        }
        else if (node.type === "StarTarget") {
            vars.add(node.name);
        }
        else if (node.type === "Tuple" || node.type === "List") {
            for (const e of node.elements) {
                this.collectTargets(e, vars);
            }
        }
    }
    compileNode(node) {
        switch (node.type) {
            case "Program":
                return node.body.map((n) => this.compileNode(n)).join("\n");
            case "FunctionDef":
                return this.compileFunctionDef(node);
            case "Class":
                return this.compileClass(node);
            case "Assignment":
                return this.compileAssignment(node);
            case "BinaryExpression":
                return this.compileBinaryExpression(node);
            case "UnaryExpression":
                return this.compileUnaryExpression(node);
            case "Literal":
                if (typeof node.value === "string") {
                    return JSON.stringify(node.value);
                }
                if (typeof node.value === "bigint") {
                    return node.value.toString() + "n";
                }
                return node.value.toString();
            case "Identifier":
                if (this.currentSelfName && node.name === this.currentSelfName) {
                    return "this";
                }
                return node.name;
            case "Return":
                return `return ${node.value ? this.compileNode(node.value) : "undefined"}`;
            case "While":
                return this.compileWhile(node);
            case "DoWhile":
                return this.compileDoWhile(node);
            case "For":
                return this.compileFor(node);
            case "If":
                return this.compileIf(node);
            case "IfExpression":
                return this.compileIfExpression(node);
            case "CallExpression":
                return this.compileCall(node);
            case "List":
                return `[${node.elements.map((e) => this.compileNode(e)).join(", ")}]`;
            case "Tuple":
                return `__tuple([${node.elements.map((e) => this.compileNode(e)).join(", ")}])`;
            case "Set":
                return `__set([${node.elements.map((e) => this.compileNode(e)).join(", ")}])`;
            case "Dict":
                return `__dict([${node.entries.map((e) => `[${this.compileNode(e.key)}, ${this.compileNode(e.value)}]`).join(", ")}])`;
            case "Bytes":
                return `__bytes(${JSON.stringify(node.value)})`;
            case "Subscript":
                return this.compileSubscript(node);
            case "ListComprehension":
                return this.compileListComprehension(node);
            case "SetComprehension":
                return this.compileSetComprehension(node);
            case "DictComprehension":
                return this.compileDictComprehension(node);
            case "FString":
                return this.compileFString(node);
            case "Yield":
                return `yield ${this.compileNode(node.value)}`;
            case "With":
                return this.compileWith(node);
            case "Lambda":
                return this.compileLambda(node);
            case "MemberAccess":
                return `${this.compileNode(node.object)}.${node.member}`;
            case "Pass":
                return "";
            case "Global":
                return "";
            case "Nonlocal":
                for (const name of node.names) {
                    let found = false;
                    // Look in enclosing function scopes (skip the current one at length-1)
                    for (let i = this.currentLocalVars.length - 2; i >= 0; i--) {
                        if (this.currentLocalVars[i].has(name)) {
                            found = true;
                            break;
                        }
                    }
                    if (!found) {
                        throw new Error(`SyntaxError: no binding for nonlocal '${name}' found`);
                    }
                }
                return "";
            case "StarTarget":
                throw new Error("StarTarget can only be used in assignment unpacking");
            default:
                throw new Error(`Unknown node type: ${node.type}`);
        }
    }
    compileFunctionDef(node) {
        const isGenerator = this.containsYield(node.body);
        const funcType = isGenerator ? "async function*" : "async function";
        // Evaluate default parameters at definition time
        let preJs = "";
        const params = [];
        for (const p of node.params) {
            if (p.defaultValue) {
                const tmpDef = this.nextTmp(`default_${node.name}_${p.name}`);
                preJs += `${this.indent()}const ${tmpDef} = ${this.compileNode(p.defaultValue)};\n`;
                params.push(`${p.name} = ${tmpDef}`);
            }
            else {
                params.push(p.name);
            }
        }
        let js = preJs;
        js += `${this.indent()}${node.name} = ${funcType}(${params.join(", ")}) {\n`;
        this.indentLevel++;
        const localVars = this.collectAssignedVars(node.body);
        for (const p of node.params)
            localVars.delete(p.name);
        if (localVars.size > 0) {
            js += `${this.indent()}let ${Array.from(localVars).join(", ")};\n`;
        }
        this.currentLocalVars.push(localVars);
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled) {
                const needsSemicolon = ![
                    "If",
                    "While",
                    "DoWhile",
                    "For",
                    "FunctionDef",
                    "With",
                ].includes(stmt.type);
                js += `${this.indent()}${compiled}${needsSemicolon ? ";" : ""}\n`;
            }
        }
        this.currentLocalVars.pop();
        this.indentLevel--;
        js += `${this.indent()}};\n`;
        const argNames = node.params.map((p) => JSON.stringify(p.name)).join(", ");
        js += `${this.indent()}${node.name}.__arg_names = [${argNames}];`;
        return js;
    }
    compileClass(node) {
        const base = node.bases.length > 0
            ? ` extends ${this.compileNode(node.bases[0])}`
            : "";
        const metadata = [];
        let preClassJs = "";
        // 1. Pre-calculate default parameters in the outer scope
        for (const bodyNode of node.body) {
            if (bodyNode.type === "FunctionDef") {
                const remainingParams = bodyNode.params.slice(1);
                for (const p of remainingParams) {
                    if (p.defaultValue) {
                        const tmpDef = this.nextTmp(`default_${bodyNode.name}_${p.name}`);
                        preClassJs += `const ${tmpDef} = ${this.compileNode(p.defaultValue)};\n${this.indent()}`;
                        p.__tmp_def_name = tmpDef;
                    }
                }
                const argNames = remainingParams
                    .map((p) => JSON.stringify(p.name))
                    .join(", ");
                if (bodyNode.name === "__init__") {
                    metadata.push(`${node.name}.__init_arg_names = [${argNames}];`);
                }
                else {
                    metadata.push(`${node.name}.prototype.${bodyNode.name}.__arg_names = [${argNames}];`);
                }
            }
        }
        // 2. Build class body
        let classJs = `${node.name} = class${base} {\n`;
        this.indentLevel++;
        for (const bodyNode of node.body) {
            if (bodyNode.type === "FunctionDef") {
                classJs += this.compileClassMethod(bodyNode, node.bases.length > 0);
            }
            else if (bodyNode.type === "Assignment") {
                for (const target of bodyNode.targets) {
                    if (target.type === "Identifier") {
                        classJs += `${this.indent()}static ${target.name} = ${this.compileNode(bodyNode.value)};\n`;
                    }
                }
            }
        }
        this.indentLevel--;
        classJs += `${this.indent()}}`;
        let finalJs = preClassJs + classJs + ";\n";
        finalJs += `${this.indent()}${node.name}.__is_class__ = true;\n`;
        finalJs += metadata.map((m) => `${this.indent()}${m}`).join("\n");
        return finalJs;
    }
    compileClassMethod(node, isDerived) {
        const isConstructor = node.name === "__init__";
        const methodName = isConstructor ? "constructor" : node.name;
        if (isConstructor) {
            if (isDerived) {
                const firstStmt = node.body[0];
                const isSuperInit = firstStmt &&
                    firstStmt.type === "CallExpression" &&
                    typeof firstStmt.callee !== "string" &&
                    firstStmt.callee.type === "MemberAccess" &&
                    firstStmt.callee.member === "__init__" &&
                    typeof firstStmt.callee.object !== "string" &&
                    firstStmt.callee.object.type === "CallExpression" &&
                    firstStmt.callee.object.callee === "super";
                if (!isSuperInit) {
                    throw new Error("SyntaxError: derived class __init__ must call super().__init__() as first statement");
                }
            }
            // Check for illegal await in constructor
            this.checkForAwait(node.body, "class constructor");
        }
        const isGenerator = this.containsYield(node.body);
        if (isGenerator) {
            throw new Error("Generators in classes not fully supported in Step 19");
        }
        const selfName = node.params.length > 0 ? node.params[0].name : null;
        const remainingParams = node.params.slice(1);
        const params = [];
        for (const p of remainingParams) {
            if (p.defaultValue) {
                params.push(`${p.name} = ${p.__tmp_def_name}`);
            }
            else {
                params.push(p.name);
            }
        }
        let js = `${this.indent()}${methodName === "constructor" ? "" : "async "}${methodName}(${params.join(", ")}) {\n`;
        this.indentLevel++;
        const localVars = this.collectAssignedVars(node.body);
        for (const p of node.params)
            localVars.delete(p.name);
        if (localVars.size > 0) {
            js += `${this.indent()}let ${Array.from(localVars).join(", ")};\n`;
        }
        const oldSelf = this.currentSelfName;
        this.currentSelfName = selfName;
        this.currentLocalVars.push(localVars);
        let selfInjected = false;
        // Map 'self' to 'this' immediately if NOT a derived constructor
        if (selfName && (!isConstructor || !isDerived)) {
            js += `${this.indent()}const ${selfName} = this;\n`;
            selfInjected = true;
        }
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled) {
                const needsSemicolon = ![
                    "If",
                    "While",
                    "DoWhile",
                    "For",
                    "FunctionDef",
                    "With",
                    "Class",
                ].includes(stmt.type);
                js += `${this.indent()}${compiled}${needsSemicolon ? ";" : ""}\n`;
                // If this was a super().__init__ call, inject self right after
                if (isConstructor &&
                    isDerived &&
                    !selfInjected &&
                    selfName &&
                    compiled.startsWith("super(")) {
                    js += `${this.indent()}const ${selfName} = this;\n`;
                    selfInjected = true;
                }
            }
        }
        this.currentLocalVars.pop();
        this.currentSelfName = oldSelf;
        // Fallback: inject self if still missing
        if (selfName && !selfInjected) {
            js += `${this.indent()}const ${selfName} = this;\n`;
        }
        this.indentLevel--;
        js += `${this.indent()}}\n`;
        return js;
    }
    checkForAwait(nodes, context) {
        const stack = [...nodes];
        while (stack.length > 0) {
            const node = stack.pop();
            if (node.type === "CallExpression") {
                const isSuperInit = typeof node.callee !== "string" &&
                    node.callee.type === "MemberAccess" &&
                    node.callee.member === "__init__" &&
                    typeof node.callee.object !== "string" &&
                    node.callee.object.type === "CallExpression" &&
                    node.callee.object.callee === "super";
                if (!isSuperInit) {
                    throw new Error(`SyntaxError: 'await' not allowed in ${context}`);
                }
                // super().__init__ is sync, but its arguments might have awaits
                for (const arg of node.args)
                    stack.push(arg.value);
                continue;
            }
            if (node.type === "ListComprehension" ||
                node.type === "SetComprehension" ||
                node.type === "DictComprehension" ||
                node.type === "Yield") {
                throw new Error(`SyntaxError: 'await' not allowed in ${context}`);
            }
            if (node.type === "BinaryExpression") {
                if (node.operator === "and" || node.operator === "or") {
                    throw new Error(`SyntaxError: 'await' not allowed in ${context}`);
                }
                stack.push(node.left, node.right);
            }
            else if (node.type === "If") {
                stack.push(node.condition);
                stack.push(...node.thenBranch);
                if (node.elseBranch)
                    stack.push(...node.elseBranch);
            }
            else if (node.type === "While" || node.type === "DoWhile") {
                stack.push(node.condition);
                stack.push(...node.body);
            }
            else if (node.type === "For") {
                if (node.iterable)
                    stack.push(node.iterable);
                stack.push(...node.body);
            }
            else if (node.type === "With") {
                stack.push(node.expression);
                stack.push(...node.body);
            }
            else if (node.type === "Assignment") {
                stack.push(node.value);
            }
            else if (node.type === "Return") {
                if (node.value)
                    stack.push(node.value);
            }
        }
    }
    containsYield(nodes) {
        for (const node of nodes) {
            if (node.type === "Yield")
                return true;
            if ("body" in node && Array.isArray(node.body)) {
                if (this.containsYield(node.body))
                    return true;
            }
            if (node.type === "If") {
                if (this.containsYield(node.thenBranch))
                    return true;
                if (node.elseBranch && this.containsYield(node.elseBranch))
                    return true;
            }
        }
        return false;
    }
    compileAssignment(node) {
        const val = this.compileNode(node.value);
        if (node.targets.length === 1) {
            const target = node.targets[0];
            if (target.type === "Identifier") {
                return `${target.name} = ${val}`;
            }
            if (target.type === "MemberAccess") {
                return `${this.compileNode(target.object)}.${target.member} = ${val}`;
            }
            if (target.type === "Subscript") {
                if (target.index.type === "Slice") {
                    throw new Error("Slice assignment not supported in Step 19");
                }
                const obj = this.compileNode(target.value);
                const idx = this.compileNode(target.index);
                return `__set_item(${obj}, ${idx}, ${val})`;
            }
        }
        const starIndex = node.targets.findIndex((t) => t.type === "StarTarget");
        const tmp = this.nextTmp("assign");
        let js = `((() => {\n`;
        this.indentLevel++;
        js += `${this.indent()}const ${tmp} = __unpack(${val}, ${node.targets.length}, ${starIndex});\n`;
        for (let i = 0; i < node.targets.length; i++) {
            const target = node.targets[i];
            let valueExpr;
            if (starIndex !== -1 && i === starIndex) {
                const tailCount = node.targets.length - 1 - starIndex;
                valueExpr = `${tmp}.slice(${starIndex}, ${tmp}.length - ${tailCount})`;
            }
            else if (starIndex !== -1 && i > starIndex) {
                const tailCount = node.targets.length - 1 - starIndex;
                const offset = i - starIndex;
                valueExpr = `${tmp}[${tmp}.length - ${tailCount - offset + 1}]`;
            }
            else {
                valueExpr = `${tmp}[${i}]`;
            }
            if (target.type === "Identifier" || target.type === "StarTarget") {
                js += `${this.indent()}${target.name} = ${valueExpr};\n`;
            }
            else if (target.type === "MemberAccess") {
                js += `${this.indent()}${this.compileNode(target.object)}.${target.member} = ${valueExpr};\n`;
            }
            else if (target.type === "Subscript") {
                if (target.index.type === "Slice") {
                    throw new Error("Slice assignment not supported in Step 19");
                }
                const obj = this.compileNode(target.value);
                const idx = this.compileNode(target.index);
                js += `${this.indent()}__set_item(${obj}, ${idx}, ${valueExpr});\n`;
            }
        }
        js += `${this.indent()}return ${tmp};\n`;
        this.indentLevel--;
        js += `${this.indent()}})())`;
        return js;
    }
    compileBinaryExpression(node) {
        const left = this.compileNode(node.left);
        const right = this.compileNode(node.right);
        const op = node.operator;
        if (op === "and") {
            return `(await __and(async () => ${left}, async () => ${right}))`;
        }
        if (op === "or") {
            return `(await __or(async () => ${left}, async () => ${right}))`;
        }
        if (op === "not in") {
            return `(!__in(${left}, ${right}))`;
        }
        const helper = OP_TO_HELPER[op];
        if (helper) {
            return `${helper}(${left}, ${right})`;
        }
        throw new Error(`Unsupported binary operator: ${op}`);
    }
    compileUnaryExpression(node) {
        const arg = this.compileNode(node.argument);
        const op = node.operator;
        if (op === "not") {
            return `(!__true(${arg}))`;
        }
        if (op === "~") {
            return `__invert(${arg})`;
        }
        return `${op}${arg}`;
    }
    compileIf(node) {
        let js = `if (__true(${this.compileNode(node.condition)})) {\n`;
        this.indentLevel++;
        for (const stmt of node.thenBranch) {
            const compiled = this.compileNode(stmt);
            if (compiled) {
                const needsSemicolon = ![
                    "If",
                    "While",
                    "DoWhile",
                    "For",
                    "FunctionDef",
                    "With",
                ].includes(stmt.type);
                js += `${this.indent()}${compiled}${needsSemicolon ? ";" : ""}\n`;
            }
        }
        this.indentLevel--;
        js += `${this.indent()}}`;
        if (node.elseBranch) {
            js += ` else {\n`;
            this.indentLevel++;
            for (const stmt of node.elseBranch) {
                const compiled = this.compileNode(stmt);
                if (compiled) {
                    const needsSemicolon = ![
                        "If",
                        "While",
                        "DoWhile",
                        "For",
                        "FunctionDef",
                        "With",
                    ].includes(stmt.type);
                    js += `${this.indent()}${compiled}${needsSemicolon ? ";" : ""}\n`;
                }
            }
            this.indentLevel--;
            js += `${this.indent()}}`;
        }
        return js;
    }
    compileIfExpression(node) {
        const cond = this.compileNode(node.condition);
        const then = this.compileNode(node.thenBranch);
        const el = this.compileNode(node.elseBranch);
        return `(__true(${cond}) ? ${then} : ${el})`;
    }
    compileWhile(node) {
        let js = `while (__true(${this.compileNode(node.condition)})) {\n`;
        this.indentLevel++;
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled) {
                const needsSemicolon = ![
                    "If",
                    "While",
                    "DoWhile",
                    "For",
                    "FunctionDef",
                    "With",
                ].includes(stmt.type);
                js += `${this.indent()}${compiled}${needsSemicolon ? ";" : ""}\n`;
            }
        }
        this.indentLevel--;
        js += `${this.indent()}}`;
        return js;
    }
    compileDoWhile(node) {
        let js = `do {\n`;
        this.indentLevel++;
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled) {
                const needsSemicolon = ![
                    "If",
                    "While",
                    "DoWhile",
                    "For",
                    "FunctionDef",
                    "With",
                ].includes(stmt.type);
                js += `${this.indent()}${compiled}${needsSemicolon ? ";" : ""}\n`;
            }
        }
        this.indentLevel--;
        js += `${this.indent()}} while (__true(${this.compileNode(node.condition)}))`;
        return js;
    }
    compileFor(node) {
        if (node.iterable) {
            const iterable = this.compileNode(node.iterable);
            const tmpItem = this.nextTmp("item");
            let js = `for await (const ${tmpItem} of __iter(${iterable})) {\n`;
            this.indentLevel++;
            if (node.iterators.length === 1) {
                js += `${this.indent()}${node.iterators[0]} = ${tmpItem};\n`;
            }
            else {
                for (let i = 0; i < node.iterators.length; i++) {
                    js += `${this.indent()}${node.iterators[i]} = __item(${tmpItem}, ${i});\n`;
                }
            }
            for (const stmt of node.body) {
                const compiled = this.compileNode(stmt);
                if (compiled) {
                    const needsSemicolon = ![
                        "If",
                        "While",
                        "DoWhile",
                        "For",
                        "FunctionDef",
                        "With",
                    ].includes(stmt.type);
                    js += `${this.indent()}${compiled}${needsSemicolon ? ";" : ""}\n`;
                }
            }
            this.indentLevel--;
            js += `${this.indent()}}`;
            return js;
        }
        else if (node.start && node.stop) {
            const start = this.compileNode(node.start);
            const stop = this.compileNode(node.stop);
            const iterator = node.iterators[0];
            let js = `for (${iterator} = ${start}; __lt(${iterator}, ${stop}); ${iterator} = __add(${iterator}, 1)) {\n`;
            this.indentLevel++;
            for (const stmt of node.body) {
                const compiled = this.compileNode(stmt);
                if (compiled) {
                    const needsSemicolon = ![
                        "If",
                        "While",
                        "DoWhile",
                        "For",
                        "FunctionDef",
                        "With",
                    ].includes(stmt.type);
                    js += `${this.indent()}${compiled}${needsSemicolon ? ";" : ""}\n`;
                }
            }
            this.indentLevel--;
            js += `${this.indent()}}`;
            return js;
        }
        throw new Error("Malformed For loop node: missing iterable or range bounds");
    }
    compileCall(node) {
        const hasKeywords = node.args.some((a) => a.name !== undefined);
        if (typeof node.callee === "string") {
            const args = node.args.map((a) => this.compileNode(a.value)).join(", ");
            if (node.callee === "next") {
                if (node.args.length === 0)
                    throw new Error("next() requires at least one argument");
                const receiver = this.compileNode(node.args[0].value);
                if (node.args.length === 1) {
                    return `(await ${receiver}.next()).value`;
                }
                else {
                    const tmpRes = this.nextTmp("next_res");
                    const defaultValue = this.compileNode(node.args[1].value);
                    return `(await (async () => {
            const ${tmpRes} = await ${receiver}.next();
            return ${tmpRes}.done ? ${defaultValue} : ${tmpRes}.value;
          })())`;
                }
            }
            const isShadowed = this.isShadowed(node.callee);
            const isBuiltin = BUILTINS.has(node.callee) && !isShadowed;
            const isPreloaded = BUILTINS.has(node.callee) && !this.shadowedBuiltins.has(node.callee);
            const isAsyncBuiltin = ASYNC_BUILTINS.has(node.callee) && isBuiltin;
            const callPrefix = isBuiltin && !isPreloaded ? "__runtime." : "";
            if (hasKeywords) {
                const posArgs = node.args
                    .filter((a) => a.name === undefined)
                    .map((a) => this.compileNode(a.value));
                const kwArgs = node.args
                    .filter((a) => a.name !== undefined)
                    .map((a) => `${a.name}: ${this.compileNode(a.value)}`);
                const argsStr = `[${posArgs.join(", ")}], { ${kwArgs.join(", ")}, __is_kwargs: true }`;
                return `(await __call(${callPrefix}${node.callee}, ${argsStr}))`;
            }
            if (isBuiltin) {
                return `(${isAsyncBuiltin ? "await " : ""}${callPrefix}${node.callee}(${args}))`;
            }
            // Use __call for all non-builtin global calls to handle classes and metadata
            return `(await __call(${node.callee}, [${args}], null))`;
        }
        if (node.callee.type === "MemberAccess") {
            const objNode = node.callee.object;
            const member = node.callee.member;
            // Special handling for super().method()
            if (objNode.type === "CallExpression" &&
                typeof objNode.callee === "string" &&
                objNode.callee === "super") {
                const args = node.args.map((a) => this.compileNode(a.value)).join(", ");
                if (member === "__init__") {
                    return `super(${args})`;
                }
                return `(await super.${member}(${args}))`;
            }
            const obj = this.compileNode(objNode);
            const posArgs = node.args
                .filter((a) => a.name === undefined)
                .map((a) => this.compileNode(a.value));
            const kwArgs = node.args
                .filter((a) => a.name !== undefined)
                .map((a) => `${a.name}: ${this.compileNode(a.value)}`);
            if (BUILTINS.has(member)) {
                // Use bare name if NOT shadowed anywhere (smart preloading).
                // Otherwise fallback to __runtime for safe mapping.
                const isShadowed = this.shadowedBuiltins.has(member);
                const callee = isShadowed ? `__runtime.${member}` : member;
                const isAsync = ASYNC_BUILTINS.has(member);
                const isProtocol = member === "__enter__" || member === "__exit__";
                if (hasKeywords) {
                    const argsStr = `[${obj}, ${posArgs.join(", ")}], { ${kwArgs.join(", ")}, __is_kwargs: true }`;
                    return `(await __call(${callee}, ${argsStr}))`;
                }
                else {
                    const argsList = [obj, ...posArgs];
                    if (isProtocol) {
                        argsList.push(member); // Pass user-visible name as fallback
                    }
                    const args = argsList.join(", ");
                    return `(${isAsync ? "await " : ""}${callee}(${args}))`;
                }
            }
            // Member call for user-defined methods/classes. Use __call_method.
            const kwArgsStr = kwArgs.length > 0
                ? `{ ${kwArgs.join(", ")}, __is_kwargs: true }`
                : "null";
            return `(await __call_method(${obj}, "${member}", [${posArgs.join(", ")}], ${kwArgsStr}))`;
        }
        const callee = this.compileNode(node.callee);
        const args = node.args.map((a) => this.compileNode(a.value)).join(", ");
        return `(await __call(${callee}, [${args}], null))`;
    }
    compileSubscript(node) {
        if (node.index.type === "Slice") {
            return this.compileSlice(this.compileNode(node.value), node.index);
        }
        const obj = this.compileNode(node.value);
        const idx = this.compileNode(node.index);
        return `__item(${obj}, ${idx})`;
    }
    compileSlice(obj, slice) {
        const start = slice.start ? this.compileNode(slice.start) : "undefined";
        const stop = slice.stop ? this.compileNode(slice.stop) : "undefined";
        const step = slice.step ? this.compileNode(slice.step) : "1";
        return `__slice(${obj}, ${start}, ${stop}, ${step})`;
    }
    compileListComprehension(node) {
        const expr = this.compileNode(node.expression);
        const iterable = this.compileNode(node.iterable);
        const cond = node.condition
            ? `__true(${this.compileNode(node.condition)})`
            : "true";
        const tmpItem = this.nextTmp("item");
        return `(await (async () => {
      const res = [];
      for await (const ${tmpItem} of __iter(${iterable})) {
        const ${node.item} = ${tmpItem};
        if (${cond}) res.push(${expr});
      }
      return res;
    })())`;
    }
    compileSetComprehension(node) {
        const expr = this.compileNode(node.expression);
        const iterable = this.compileNode(node.iterable);
        const cond = node.condition
            ? `__true(${this.compileNode(node.condition)})`
            : "true";
        const tmpItem = this.nextTmp("item");
        return `(await (async () => {
      const res = new Set();
      for await (const ${tmpItem} of __iter(${iterable})) {
        const ${node.item} = ${tmpItem};
        if (${cond}) res.add(${expr});
      }
      return res;
    })())`;
    }
    compileDictComprehension(node) {
        const key = this.compileNode(node.key);
        const value = this.compileNode(node.value);
        const iterable = this.compileNode(node.iterable);
        const cond = node.condition
            ? `__true(${this.compileNode(node.condition)})`
            : "true";
        const tmpItem = this.nextTmp("item");
        return `(await (async () => {
      const res = {};
      for await (const ${tmpItem} of __iter(${iterable})) {
        const ${node.item} = ${tmpItem};
        if (${cond}) res[${key}] = ${value};
      }
      return res;
    })())`;
    }
    compileFString(node) {
        const parts = node.parts
            .map((p) => {
            if (typeof p === "string") {
                return p
                    .replace(/\\/g, "\\\\")
                    .replace(/`/g, "\\`")
                    .replace(/\$\{/g, "\\${");
            }
            return `\${str(${this.compileNode(p)})}`;
        })
            .join("");
        return `(\`${parts}\`)`;
    }
    compileWith(node) {
        const expr = this.compileNode(node.expression);
        const target = node.target;
        const tmpMgr = this.nextTmp("mgr");
        const tmpIsMethod = this.nextTmp("is_method");
        const tmpEnter = this.nextTmp("enter");
        const tmpExit = this.nextTmp("exit");
        let js = `{\n`;
        this.indentLevel++;
        js += `${this.indent()}const ${tmpMgr} = ${expr};\n`;
        js += `${this.indent()}const ${tmpIsMethod} = typeof ${tmpMgr}.__enter__ === 'function';\n`;
        // Fallback to the user-visible bare name (which correctly handles shadowing/preloading)
        js += `${this.indent()}const ${tmpEnter} = ${tmpIsMethod} ? ${tmpMgr}.__enter__.bind(${tmpMgr}) : __enter__;\n`;
        js += `${this.indent()}const ${tmpExit} = typeof ${tmpMgr}.__exit__ === 'function' ? ${tmpMgr}.__exit__.bind(${tmpMgr}) : __exit__;\n`;
        js += `${this.indent()}if (typeof ${tmpEnter} !== 'function') throw new Error("Object does not support the context manager protocol (missing __enter__)");\n`;
        js += `${this.indent()}if (typeof ${tmpExit} !== 'function') throw new Error("Object does not support the context manager protocol (missing __exit__)");\n`;
        const enterCall = `await (${tmpIsMethod} ? ${tmpEnter}() : ${tmpEnter}(${tmpMgr}))`;
        if (target) {
            js += `${this.indent()}${target} = ${enterCall};\n`;
        }
        else {
            js += `${this.indent()}${enterCall};\n`;
        }
        js += `${this.indent()}try {\n`;
        this.indentLevel++;
        for (const stmt of node.body) {
            const compiled = this.compileNode(stmt);
            if (compiled) {
                const needsSemicolon = ![
                    "If",
                    "While",
                    "DoWhile",
                    "For",
                    "FunctionDef",
                    "With",
                ].includes(stmt.type);
                js += `${this.indent()}${compiled}${needsSemicolon ? ";" : ""}\n`;
            }
        }
        this.indentLevel--;
        js += `${this.indent()}} finally {\n`;
        this.indentLevel++;
        js += `${this.indent()}await (${tmpIsMethod} ? ${tmpExit}(null, null, null) : ${tmpExit}(${tmpMgr}, null, null, null));\n`;
        this.indentLevel--;
        js += `${this.indent()}}\n`;
        this.indentLevel--;
        js += `${this.indent()}}`;
        return js;
    }
    compileLambda(node) {
        const argNames = node.params
            .map((p) => JSON.stringify(p.name))
            .join(", ");
        const hasDefaults = node.params.some((p) => p.defaultValue !== undefined);
        let lambdaBody;
        let paramsList;
        if (hasDefaults) {
            const tmpDefNames = node.params.map((p) => p.defaultValue ? this.nextTmp(`def_${p.name}`) : null);
            const preJsParts = tmpDefNames
                .map((name, i) => name
                ? `const ${name} = ${this.compileNode(node.params[i].defaultValue)};`
                : "")
                .filter((x) => x);
            const paramsWithDefaults = node.params
                .map((p, i) => tmpDefNames[i] ? `${p.name} = ${tmpDefNames[i]}` : p.name)
                .join(", ");
            paramsList = paramsWithDefaults;
            lambdaBody = `async (${paramsList}) => ${this.compileNode(node.expression)}`;
            return `((() => { 
        ${preJsParts.join(" ")} 
        const __lam = ${lambdaBody};
        __lam.__arg_names = [${argNames}];
        return __lam;
      })())`;
        }
        else {
            paramsList = node.params.map((p) => p.name).join(", ");
            lambdaBody = `async (${paramsList}) => ${this.compileNode(node.expression)}`;
            return `((() => { 
        const __lam = ${lambdaBody};
        __lam.__arg_names = [${argNames}];
        return __lam;
      })())`;
        }
    }
}
