@echo off
REM Rust-to-WASM Port (RUST)
echo Running Full Check...
echo [1/5] Formatting...
call npm run format
echo [2/5] Linting...
call npm run lint
echo [3/5] Building...
call npm run build
echo [3.5/5] Syncing samples...
xcopy /Y /S samples\*.rs pub\samples\
echo [4/5] Testing...
call npm run test
echo [5/5] UI Testing...
call npm run test:ui
if %errorlevel% neq 0 (
    echo Check failed!
    exit /b %errorlevel%
)
echo All checks passed.
