// src/compiler.ts
import {
  ProgramNode,
  ASTNode,
  FunctionDefNode,
  SliceNode,
  WithNode,
  BinaryExpressionNode,
  WhileNode,
  CallExpressionNode,
  UnaryExpressionNode,
  IfNode,
  ListComprehensionNode,
  DictComprehensionNode,
  SubscriptNode,
  ForNode,
  DoWhileNode,
  FStringNode,
  AssignmentNode,
} from "./parser.js";

const BUILTINS = new Set([
  "print",
  "sleep",
  "range",
  "len",
  "abs",
  "math",
  "int",
  "float",
  "bool",
  "chr",
  "ord",
]);

export class Compiler {
  private indentLevel: number = 0;
  private tmpCounter: number = 0;

  private indent(): string {
    return "  ".repeat(this.indentLevel);
  }

  private nextTmp(name: string): string {
    return `__tmp_${name}_${this.tmpCounter++}`;
  }

  compileJS(program: ProgramNode): string {
    let js = "// Generated by Python-to-JavaScript\n";
    js += "export async function main_wrapper(runtime) {\n";
    this.indentLevel++;
    js += `${this.indent()}const globals = Object.create(runtime);\n`;

    // Identify top-level variables and functions
    const topLevelVars = this.collectAssignedVars(program.body);
    for (const node of program.body) {
      if (node.type === "FunctionDef") {
        topLevelVars.add(node.name);
      }
    }

    // Map builtins that are not shadowed at top-level
    for (const b of BUILTINS) {
      if (!topLevelVars.has(b)) {
        js += `${this.indent()}const ${b} = runtime.${b};\n`;
      }
    }

    // Declare top-level variables (excluding functions which use 'async function')
    const varsToDeclare = new Set(topLevelVars);
    for (const node of program.body) {
      if (node.type === "FunctionDef") {
        varsToDeclare.delete(node.name);
      }
    }
    if (varsToDeclare.size > 0) {
      js += `${this.indent()}let ${Array.from(varsToDeclare).join(", ")};\n`;
    }
    js += "\n";

    // First pass: identify all functions to declare them at the top scope
    for (const node of program.body) {
      if (node.type === "FunctionDef") {
        js += this.compileNode(node) + "\n";
        js += `${this.indent()}globals.${node.name} = ${node.name};\n`;
      }
    }

    // Second pass: compile top-level statements
    let mainCalled = false;
    const statements = program.body.filter((n) => n.type !== "FunctionDef");
    for (let i = 0; i < statements.length; i++) {
      const node = statements[i];
      const isLast = i === statements.length - 1;
      const isMainCall =
        node.type === "CallExpression" &&
        (typeof node.callee === "string" ? node.callee === "main" : false);

      if (isMainCall) {
        mainCalled = true;
        if (isLast) {
          js += `${this.indent()}globals.__result__ = ${this.compileNode(node)};\n`;
          js += `${this.indent()}return globals;\n`;
          continue;
        }
      }

      const compiled = this.compileNode(node);
      if (compiled) {
        js += `${this.indent()}${compiled};\n`;
      }
    }

    // Try to call main() if it exists and hasn't been called
    if (!mainCalled) {
      js += `\n${this.indent()}if (typeof main === 'function') {\n`;
      js += `${this.indent()}  globals.__result__ = await main();\n`;
      js += `${this.indent()}}\n`;
    } else {
      // If main was called, we should have captured its result if it was the last stmt
      // but for simplicity, let's just ensure we return globals.
    }

    js += `\n${this.indent()}return globals;\n`;

    this.indentLevel--;
    js += "}\n";
    return js;
  }

  private collectAssignedVars(nodes: ASTNode[]): Set<string> {
    const vars = new Set<string>();
    const stack = [...nodes];
    while (stack.length > 0) {
      const node = stack.pop()!;
      if (node.type === "Assignment") {
        vars.add(node.target);
      } else if (node.type === "For") {
        vars.add(node.iterator);
        stack.push(...node.body);
      } else if (node.type === "With") {
        if (node.target) vars.add(node.target);
        stack.push(...node.body);
      } else if (node.type === "If") {
        stack.push(...node.thenBranch);
        if (node.elseBranch) stack.push(...node.elseBranch);
      } else if (node.type === "While" || node.type === "DoWhile") {
        stack.push(...node.body);
      }
    }
    return vars;
  }

  private compileNode(node: ASTNode): string {
    switch (node.type) {
      case "Program":
        return node.body.map((n) => this.compileNode(n)).join("\n");

      case "FunctionDef":
        return this.compileFunctionDef(node);

      case "Assignment":
        return this.compileAssignment(node);

      case "BinaryExpression":
        return this.compileBinaryExpression(node);

      case "UnaryExpression":
        return this.compileUnaryExpression(node);

      case "Literal":
        if (typeof node.value === "string") {
          return JSON.stringify(node.value);
        }
        if (typeof node.value === "bigint") {
          return node.value.toString() + "n";
        }
        return node.value.toString();

      case "Identifier":
        return node.name;

      case "Return":
        return `return ${node.value ? this.compileNode(node.value) : "undefined"}`;

      case "While":
        return this.compileWhile(node);

      case "DoWhile":
        return this.compileDoWhile(node);

      case "For":
        return this.compileFor(node);

      case "If":
        return this.compileIf(node);

      case "CallExpression":
        return this.compileCall(node);

      case "List":
        return `[${node.elements.map((e) => this.compileNode(e)).join(", ")}]`;

      case "Subscript":
        return this.compileSubscript(node);

      case "ListComprehension":
        return this.compileListComprehension(node);

      case "DictComprehension":
        return this.compileDictComprehension(node);

      case "FString":
        return this.compileFString(node);

      case "Yield":
        return `yield ${this.compileNode(node.value)}`;

      case "With":
        return this.compileWith(node);

      case "MemberAccess":
        return `${this.compileNode(node.object)}.${node.member}`;

      case "Pass":
        return "";

      default:
        throw new Error(`Unknown node type: ${(node as any).type}`);
    }
  }

  private compileFunctionDef(node: FunctionDefNode): string {
    const isGenerator = this.containsYield(node.body);
    const funcType = isGenerator ? "async function*" : "async function";
    const params = node.params.join(", ");
    let js = `${this.indent()}${funcType} ${node.name}(${params}) {\n`;
    this.indentLevel++;

    // Declare local variables (excluding params)
    const localVars = this.collectAssignedVars(node.body);
    for (const p of node.params) localVars.delete(p);
    if (localVars.size > 0) {
      js += `${this.indent()}let ${Array.from(localVars).join(", ")};\n`;
    }

    for (const stmt of node.body) {
      const compiled = this.compileNode(stmt);
      if (compiled) {
        js += `${this.indent()}${compiled};\n`;
      }
    }
    this.indentLevel--;
    js += `${this.indent()}}\n`;
    return js;
  }

  private containsYield(nodes: ASTNode[]): boolean {
    for (const node of nodes) {
      if (node.type === "Yield") return true;
      if ("body" in node && Array.isArray(node.body)) {
        if (this.containsYield(node.body)) return true;
      }
      if (node.type === "If") {
        if (this.containsYield(node.thenBranch)) return true;
        if (node.elseBranch && this.containsYield(node.elseBranch)) return true;
      }
    }
    return false;
  }

  private compileAssignment(node: AssignmentNode): string {
    return `${node.target} = ${this.compileNode(node.value)}`;
  }

  private compileBinaryExpression(node: BinaryExpressionNode): string {
    const left = this.compileNode(node.left);
    const right = this.compileNode(node.right);
    let op = node.operator;

    if (op === "and") {
      const tmp = this.nextTmp("and");
      return `(await (async () => {
        const ${tmp} = ${left};
        return runtime._is_truthy(${tmp}) ? ${right} : ${tmp};
      })())`;
    }
    if (op === "or") {
      const tmp = this.nextTmp("or");
      return `(await (async () => {
        const ${tmp} = ${left};
        return runtime._is_truthy(${tmp}) ? ${tmp} : ${right};
      })())`;
    }

    if (op === "==") op = "===";
    if (op === "!=") op = "!==";

    // Use a runtime helper for other operators to handle BigInt mixing and Python-specific behaviors
    return `(await runtime._binop("${op}", ${left}, ${right}))`;
  }

  private compileUnaryExpression(node: UnaryExpressionNode): string {
    const arg = this.compileNode(node.argument);
    const op = node.operator;
    if (op === "not") {
      return `(!runtime._is_truthy(${arg}))`;
    }
    return `${op}${arg}`;
  }

  private compileIf(node: IfNode): string {
    let js = `if (runtime._is_truthy(${this.compileNode(node.condition)})) {\n`;
    this.indentLevel++;
    for (const stmt of node.thenBranch) {
      const compiled = this.compileNode(stmt);
      if (compiled) js += `${this.indent()}${compiled};\n`;
    }
    this.indentLevel--;
    js += `${this.indent()}}`;

    if (node.elseBranch) {
      js += ` else {\n`;
      this.indentLevel++;
      for (const stmt of node.elseBranch) {
        const compiled = this.compileNode(stmt);
        if (compiled) js += `${this.indent()}${compiled};\n`;
      }
      this.indentLevel--;
      js += `${this.indent()}}`;
    }
    return js;
  }

  private compileWhile(node: WhileNode): string {
    let js = `while (runtime._is_truthy(${this.compileNode(node.condition)})) {\n`;
    this.indentLevel++;
    for (const stmt of node.body) {
      const compiled = this.compileNode(stmt);
      if (compiled) js += `${this.indent()}${compiled};\n`;
    }
    this.indentLevel--;
    js += `${this.indent()}}`;
    return js;
  }

  private compileDoWhile(node: DoWhileNode): string {
    let js = `do {\n`;
    this.indentLevel++;
    for (const stmt of node.body) {
      const compiled = this.compileNode(stmt);
      if (compiled) js += `${this.indent()}${compiled};\n`;
    }
    this.indentLevel--;
    js += `${this.indent()}} while (runtime._is_truthy(${this.compileNode(node.condition)}))`;
    return js;
  }

  private compileFor(node: ForNode): string {
    if (node.iterable) {
      const iterable = this.compileNode(node.iterable);
      const tmpItem = this.nextTmp("item");
      // Use a runtime helper to handle both sync and async iterators efficiently
      let js = `for await (const ${tmpItem} of (runtime._iter ? runtime._iter(${iterable}) : ${iterable})) {\n`;
      this.indentLevel++;
      js += `${this.indent()}${node.iterator} = ${tmpItem};\n`;
      for (const stmt of node.body) {
        const compiled = this.compileNode(stmt);
        if (compiled) js += `${this.indent()}${compiled};\n`;
      }
      this.indentLevel--;
      js += `${this.indent()}}`;
      return js;
    } else if (node.start && node.stop) {
      const start = this.compileNode(node.start);
      const stop = this.compileNode(node.stop);
      // Use the already-declared iterator directly
      let js = `for (${node.iterator} = ${start}; ${node.iterator} < ${stop}; ${node.iterator}++) {\n`;
      this.indentLevel++;
      for (const stmt of node.body) {
        const compiled = this.compileNode(stmt);
        if (compiled) js += `${this.indent()}${compiled};\n`;
      }
      this.indentLevel--;
      js += `${this.indent()}}`;
      return js;
    }
    throw new Error(
      "Malformed For loop node: missing iterable or range bounds",
    );
  }

  private compileCall(node: CallExpressionNode): string {
    const args = node.args.map((a) => this.compileNode(a)).join(", ");

    if (typeof node.callee === "string") {
      if (node.callee === "next") {
        if (node.args.length === 0)
          throw new Error("next() requires at least one argument");
        const receiver = this.compileNode(node.args[0]);
        if (node.args.length === 1) {
          return `(await ${receiver}.next()).value`;
        } else {
          // next(g, default)
          const tmpRes = this.nextTmp("next_res");
          const defaultValue = this.compileNode(node.args[1]);
          return `(await (async () => {
            const ${tmpRes} = await ${receiver}.next();
            return ${tmpRes}.done ? ${defaultValue} : ${tmpRes}.value;
          })())`;
        }
      }
      return `(await ${node.callee}(${args}))`;
    }

    if (node.callee.type === "MemberAccess") {
      const obj = this.compileNode(node.callee.object);
      const member = node.callee.member;
      const tmpObj = this.nextTmp("obj");
      const tmpFallback = this.nextTmp("fallback");

      // Handle fallback to runtime for member calls (Python-style methods)
      return `(await (async () => {
        const ${tmpObj} = ${obj};
        if (typeof ${tmpObj}.${member} === 'function') {
          return await ${tmpObj}.${member}(${args});
        }
        const ${tmpFallback} = globals.${member};
        if (typeof ${tmpFallback} === 'function') {
          return await ${tmpFallback}(${tmpObj}${args ? ", " + args : ""});
        }
        throw new Error("${member} is not a function");
      })())`;
    }

    const callee = this.compileNode(node.callee);
    return `(await ${callee}(${args}))`;
  }

  private compileSubscript(node: SubscriptNode): string {
    if (node.index.type === "Slice") {
      return this.compileSlice(this.compileNode(node.value), node.index);
    }

    const tmpObj = this.nextTmp("obj");
    const tmpIdx = this.nextTmp("idx");
    const obj = this.compileNode(node.value);
    const idx = this.compileNode(node.index);

    return `(await (async () => {
      const ${tmpObj} = ${obj};
      const ${tmpIdx} = ${idx};
      if (typeof ${tmpIdx} === 'number' && ${tmpIdx} < 0 && (Array.isArray(${tmpObj}) || typeof ${tmpObj} === 'string')) {
        return ${tmpObj}[${tmpObj}.length + ${tmpIdx}];
      }
      return ${tmpObj}[${tmpIdx}];
    })())`;
  }

  private compileSlice(obj: string, slice: SliceNode): string {
    const start = slice.start ? this.compileNode(slice.start) : "undefined";
    const stop = slice.stop ? this.compileNode(slice.stop) : "undefined";
    const step = slice.step ? this.compileNode(slice.step) : "1";

    return `runtime._slice(${obj}, ${start}, ${stop}, ${step})`;
  }

  private compileListComprehension(node: ListComprehensionNode): string {
    const expr = this.compileNode(node.expression);
    const iterable = this.compileNode(node.iterable);
    const cond = node.condition
      ? `runtime._is_truthy(${this.compileNode(node.condition)})`
      : "true";
    const tmpItem = this.nextTmp("item");

    return `(await (async () => {
      const res = [];
      for await (const ${tmpItem} of (runtime._iter ? runtime._iter(${iterable}) : ${iterable})) {
        const ${node.item} = ${tmpItem};
        if (${cond}) res.push(${expr});
      }
      return res;
    })())`;
  }

  private compileDictComprehension(node: DictComprehensionNode): string {
    const key = this.compileNode(node.key);
    const value = this.compileNode(node.value);
    const iterable = this.compileNode(node.iterable);
    const cond = node.condition
      ? `runtime._is_truthy(${this.compileNode(node.condition)})`
      : "true";
    const tmpItem = this.nextTmp("item");

    return `(await (async () => {
      const res = {};
      for await (const ${tmpItem} of (runtime._iter ? runtime._iter(${iterable}) : ${iterable})) {
        const ${node.item} = ${tmpItem};
        if (${cond}) res[${key}] = ${value};
      }
      return res;
    })())`;
  }

  private compileFString(node: FStringNode): string {
    const parts = node.parts
      .map((p) => {
        if (typeof p === "string") return JSON.stringify(p);
        return `String(${this.compileNode(p)})`;
      })
      .join(" + ");
    return `(${parts})`;
  }

  private compileWith(node: WithNode): string {
    const expr = this.compileNode(node.expression);
    const target = node.target;
    const tmpMgr = this.nextTmp("mgr");
    const tmpIsMethod = this.nextTmp("is_method");
    const tmpEnter = this.nextTmp("enter");
    const tmpExit = this.nextTmp("exit");

    let js = `{\n`;
    this.indentLevel++;
    js += `${this.indent()}const ${tmpMgr} = ${expr};\n`;
    js += `${this.indent()}const ${tmpIsMethod} = typeof ${tmpMgr}.__enter__ === 'function';\n`;
    js += `${this.indent()}const ${tmpEnter} = ${tmpIsMethod} ? ${tmpMgr}.__enter__.bind(${tmpMgr}) : globals.__enter__;\n`;
    js += `${this.indent()}const ${tmpExit} = typeof ${tmpMgr}.__exit__ === 'function' ? ${tmpMgr}.__exit__.bind(${tmpMgr}) : globals.__exit__;\n`;

    js += `${this.indent()}if (typeof ${tmpEnter} !== 'function') throw new Error("Object does not support the context manager protocol (missing __enter__)");\n`;
    js += `${this.indent()}if (typeof ${tmpExit} !== 'function') throw new Error("Object does not support the context manager protocol (missing __exit__)");\n`;

    const enterCall = `await (${tmpIsMethod} ? ${tmpEnter}() : ${tmpEnter}(${tmpMgr}))`;
    if (target) {
      js += `${this.indent()}${target} = ${enterCall};\n`;
    } else {
      js += `${this.indent()}${enterCall};\n`;
    }

    js += `${this.indent()}try {\n`;
    this.indentLevel++;
    for (const stmt of node.body) {
      const compiled = this.compileNode(stmt);
      if (compiled) js += `${this.indent()}${compiled};\n`;
    }
    this.indentLevel--;
    js += `${this.indent()}} finally {\n`;
    this.indentLevel++;
    js += `${this.indent()}await (${tmpIsMethod} ? ${tmpExit}(null, null, null) : ${tmpExit}(${tmpMgr}, null, null, null));\n`;
    this.indentLevel--;
    js += `${this.indent()}}\n`;
    this.indentLevel--;
    js += `${this.indent()}}`;
    return js;
  }
}
